- hosts: localhost
  connection: local
  tasks:
  - name: Creating the lambda function
    shell: aws lambda create-function --function-name "{{function_name}}" --runtime "{{runtime}}" --zip-file "fileb://{{zip_file_name_with_ext}}" --handler "{{function_handler}}" --role "{{lambda_role_arn}}" --timeout 300 --region "{{region}}"| jq -r .FunctionArn
    register: var1
  - debug:
      msg: "{{var1}}"
  - name: Create Restful API
    shell: aws apigateway create-rest-api --name "{{function_name}}" --description 'API Gateway to trigger lambda for patching' --region "{{region}}"| jq -r .id
    register: var2
    when: var1.stdout != ""
  - debug:
      msg: "{{var2}}"
  - name: Integrating Lambda with the API Gateway
    shell: aws lambda add-permission --region "{{region}}" --function-name {{LAMBDA-FUNCTION-NAME}} --statement-id "{{var2.stdout}}" --action "lambda:InvokeFunction" --principal api.amazonaws.com --source-arn 'arn:aws:apigateway:"{{region}}"::/restapis/"{{var2.stdout}}"/stages/default'
    when: var2.stdout != ""
    register: var3
  - debug:
      msg: "{{var3.stdout}}"
      
      
