
  
- hosts: localhost
  connection: local
  
  tasks:
  - name: Create a new Parameter for Baseline Name
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/baseline/name' --value "{{Baseline_Name}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Operating System
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/baseline/OS" --value "{{Patch_Operating_System}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Severity
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/baseline/severity' --value "{{Severity}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Classification
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/baseline/classification' --value "{{Classification}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Approve After Days
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/baseline/approve_after_days' --value "{{Approve_after_days}}" --type "String" --region "{{region}}" --overwrite
  
  - name: Create a new Parameter for Baseline Description
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/baseline/desc' --value "{{Baseline_description}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Patch Group
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/patchgroup/name' --value "{{patch_group}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Maintenance Window Name
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/name' --value "{{Maintenance_Window_Name}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Maintenance Window Schedule
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/schedule' --value "{{Maintenance_Schedule}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Maintenance Window Duration
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/duration' --value "{{Maintenance_Duration}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Maintenance Window Cutoff
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/cutoff' --value "{{Maintenance_Cutoff}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Maintenance Window Target Owner Information
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/targetownerinfo' --value "{{Target_Owner_Information}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for Maintenance Window Task
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/task' --value "{{Task}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for  Maintenance Window Service Role ARN
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/maintenancewindow/servicerolearn' --value "{{Service_Role_arn}}" --type "String" --region "{{region}}" --overwrite
    
  - name: Create a new Parameter for  Region
    shell: aws ssm put-parameter --name '/patch/"{{PatchTag}}"/region' --value "{{region}}" --type "String" --region "{{region}}" --overwrite
